/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingRoutinesRouteImport } from './routes/onboarding.routines'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingConnectRouteImport } from './routes/onboarding.connect'
import { Route as OnboardingAssistantRouteImport } from './routes/onboarding.assistant'
import { Route as AppTodoRouteImport } from './routes/_app.todo'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPowersRouteImport } from './routes/_app.powers'
import { Route as AppPeopleRouteImport } from './routes/_app.people'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppInboxIndexRouteImport } from './routes/_app.inbox.index'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app.people.$personId'
import { Route as AppInboxFinishedRouteImport } from './routes/_app.inbox.finished'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoutinesRoute = OnboardingRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAssistantRoute = OnboardingAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppTodoRoute = AppTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPowersRoute = AppPowersRouteImport.update({
  id: '/powers',
  path: '/powers',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppInboxFinishedRoute = AppInboxFinishedRouteImport.update({
  id: '/finished',
  path: '/finished',
  getParentRoute: () => AppInboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/home': typeof AppHomeRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/meetings': typeof AppMeetingsRoute
  '/memory': typeof AppMemoryRoute
  '/people': typeof AppPeopleRouteWithChildren
  '/powers': typeof AppPowersRoute
  '/settings': typeof AppSettingsRoute
  '/todo': typeof AppTodoRoute
  '/onboarding/assistant': typeof OnboardingAssistantRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/routines': typeof OnboardingRoutinesRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/inbox/finished': typeof AppInboxFinishedRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/inbox/': typeof AppInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AppCalendarRoute
  '/home': typeof AppHomeRoute
  '/meetings': typeof AppMeetingsRoute
  '/memory': typeof AppMemoryRoute
  '/people': typeof AppPeopleRouteWithChildren
  '/powers': typeof AppPowersRoute
  '/settings': typeof AppSettingsRoute
  '/todo': typeof AppTodoRoute
  '/onboarding/assistant': typeof OnboardingAssistantRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/routines': typeof OnboardingRoutinesRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/inbox/finished': typeof AppInboxFinishedRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/inbox': typeof AppInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/people': typeof AppPeopleRouteWithChildren
  '/_app/powers': typeof AppPowersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/todo': typeof AppTodoRoute
  '/onboarding/assistant': typeof OnboardingAssistantRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/routines': typeof OnboardingRoutinesRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/inbox/finished': typeof AppInboxFinishedRoute
  '/_app/people/$personId': typeof AppPeoplePersonIdRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/calendar'
    | '/home'
    | '/inbox'
    | '/meetings'
    | '/memory'
    | '/people'
    | '/powers'
    | '/settings'
    | '/todo'
    | '/onboarding/assistant'
    | '/onboarding/connect'
    | '/onboarding/profile'
    | '/onboarding/routines'
    | '/onboarding/'
    | '/inbox/finished'
    | '/people/$personId'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/home'
    | '/meetings'
    | '/memory'
    | '/people'
    | '/powers'
    | '/settings'
    | '/todo'
    | '/onboarding/assistant'
    | '/onboarding/connect'
    | '/onboarding/profile'
    | '/onboarding/routines'
    | '/onboarding'
    | '/inbox/finished'
    | '/people/$personId'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/calendar'
    | '/_app/home'
    | '/_app/inbox'
    | '/_app/meetings'
    | '/_app/memory'
    | '/_app/people'
    | '/_app/powers'
    | '/_app/settings'
    | '/_app/todo'
    | '/onboarding/assistant'
    | '/onboarding/connect'
    | '/onboarding/profile'
    | '/onboarding/routines'
    | '/onboarding/'
    | '/_app/inbox/finished'
    | '/_app/people/$personId'
    | '/_app/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/routines': {
      id: '/onboarding/routines'
      path: '/routines'
      fullPath: '/onboarding/routines'
      preLoaderRoute: typeof OnboardingRoutinesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/assistant': {
      id: '/onboarding/assistant'
      path: '/assistant'
      fullPath: '/onboarding/assistant'
      preLoaderRoute: typeof OnboardingAssistantRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/todo': {
      id: '/_app/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AppTodoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/powers': {
      id: '/_app/powers'
      path: '/powers'
      fullPath: '/powers'
      preLoaderRoute: typeof AppPowersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/people/$personId': {
      id: '/_app/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/_app/inbox/finished': {
      id: '/_app/inbox/finished'
      path: '/finished'
      fullPath: '/inbox/finished'
      preLoaderRoute: typeof AppInboxFinishedRouteImport
      parentRoute: typeof AppInboxRoute
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxFinishedRoute: typeof AppInboxFinishedRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxFinishedRoute: AppInboxFinishedRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppPeopleRouteChildren {
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
}

const AppPeopleRouteChildren: AppPeopleRouteChildren = {
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
}

const AppPeopleRouteWithChildren = AppPeopleRoute._addFileChildren(
  AppPeopleRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppPeopleRoute: typeof AppPeopleRouteWithChildren
  AppPowersRoute: typeof AppPowersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodoRoute: typeof AppTodoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppHomeRoute: AppHomeRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppPeopleRoute: AppPeopleRouteWithChildren,
  AppPowersRoute: AppPowersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodoRoute: AppTodoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAssistantRoute: typeof OnboardingAssistantRoute
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingRoutinesRoute: typeof OnboardingRoutinesRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAssistantRoute: OnboardingAssistantRoute,
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingRoutinesRoute: OnboardingRoutinesRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
